name: Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          repository: 'emersonmx/emersonmx.github.io'
          path: public

      - name: Build and Deploy
        run: |
          ls -R public

          pushd public ; git ls-files | xargs rm ; popd
          ls -R public

          make build
          ls -R public

          pushd public
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git commit -m "Updated at $(date --iso-8601=minutes)"
          #git push
          git log
          popd
