name: Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          repository: 'emersonmx/emersonmx.github.io'
          path: public
          token: ${{ secrets.GH_PAT }}

      - uses: extractions/setup-just@v3

      - uses: peaceiris/actions-hugo@v3

      - name: Clean
        run: |
          pushd public
          git ls-files | xargs rm -v
          popd

      - name: Build
        run: |
          just build

      - name: Deploy
        run: |
          pushd public
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git commit -m "Updated at $(date --iso-8601=minutes)" && git push
          popd
